### ISSUE TITLE
Retornar apenas o status http nos endpoints

### ISSUE THREAD

**Issue by arthurs159** [emeath/loja-anime#1]
Olá, percebi que no projeto, você retorna string dentro do body caso dê algum erro, acho legal apenas retornar o status http mesmo, pois seria isso que o front consumiria,  sabe?

```java
    @GetMapping("/{id}")
    public ResponseEntity<Object> getAutorById(@PathVariable Long id){
        Optional<AutorModel> autorModelOptional = autorService.findById(id);
        if (!autorModelOptional.isPresent()){
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Autor id: " + id + " não encontrado!");
        }
        return ResponseEntity.status(HttpStatus.OK).body(autorService.findById(id));
    }
```
No ultimo return, você utiliza novamente o findByid, acho que não precisaria, só utilizar a variavel do optional lá de cima.
Acho que daria pra corrigir isso em todos os endpoints, ficaria bem legal!!!

`Dica: Você pode utilizar o isEmpty nos optionals ao invés de utilizar o isPresent e depois nega-lo`

**Comment by emeath** [comment]
Muito obrigado pelas sugestões. Alterei conforme instruido nestes commits:

- 124b28575e558f9ac2bcb44d09ab8b94aac42d1f
- ed70825b10639048e766950cc774fb439456190b
- 53e691c7363f82a3bbf73c5bb64716048b0524a8


Em relação ao `isEmpty()`, eu estava utilizando ele, mas quando fui subir o projeto para o Herok houve erro porque lá é utilizado java 8 e parece que esse método não é disponível nessa versão. Neste commit: 7d49ffe69c5e53b24020e71b1aa12794ec48059e eu fiz a alteração para `!isPresent()`
